### ISSUE TITLE
Plasma 5.8.2 - yakuake-session doesn't focus a new opened window

### ISSUE THREAD

**Issue by itaranto** [aplatanado/yakuake-session#11]
Running yakuake-session from konsole or by launching directly from dolphin (Shift+F4) does not shows the yakuake window, although it was opened in the background.
The error message is:
$ yakuake-session
Cannot find '.Get' in object /yakuake/MainWindow_1 at org.kde.yakuake
[2]+  Done                    yakuake

Tested on openSUSE: Leap 42.2 with KDE Plasma 5.8.2

**Comment by aplatanado** [comment]
Hi,

Thank for report this issue. I don't have Plasma 5.6 yet so could you run:

qdbus org.kde.yakuake /yakuake/MainWindow_1

and send me its output?

**Comment by itaranto** [comment]
Here's the output:
$ qdbus org.kde.yakuake /yakuake/MainWindow_1
Error: org.freedesktop.DBus.Error.UnknownObject
No such object path '/yakuake/MainWindow_1'

**Comment by aplatanado** [comment]
Ok. I suppose that  /yakuake/MainWindow_1 exists.

And?

$ qdbus org.kde.yakuake

**Comment by itaranto** [comment]
Sorry I forgot you haven't Plasma 5.8 to test:
$ qdbus org.kde.yakuake 
/
/MainApplication
/Sessions
/Sessions/1
/Windows
/Windows/1
/org
/org/kde
/org/kde/yakuake
/yakuake
/yakuake/sessions
/yakuake/tabs
/yakuake/window

**Comment by aplatanado** [comment]
Thank you.

There is a related bug filed 5 months ago:
https://bugs.kde.org/show_bug.cgi?id=364705

**Comment by Jacobtey** [comment]
The same error n Manjaro Linux(

**Comment by aplatanado** [comment]
Yakuake-session now uses xprop command as fallback to get if the windows is visible when  /yakuake/MainWindow_1 interface isn't available.

**Comment by itaranto** [comment]
Thanks!
