### ISSUE TITLE
-e only works in the simplest of scenarios

### ISSUE THREAD

**Issue by rulatir** [aplatanado/yakuake-session#12]
The handling of the `-e` option is currently rather deficient.
* it does not support built-in bash commands, so you cannot use `source foo fooArg` as the argument to `-e`
* it doesn't stop interpreting options after `-e` nor does it support `--`, so it's impossible to pass a command that will itself take options; in particular it is impossible to pass `bash -c -i -- source foo fooArg` as the command 
* quoting the whole command doesn't work either

**Comment by aplatanado** [comment]
Yes. `-e` option isn't very useful. I will change it to behave more like xterm or konsole `-e` option. What was my original intention.

Thank you.
