### ISSUE TITLE
Is Bash assumed as the default shell?

### ISSUE THREAD

**Issue by adrfantini** [aplatanado/yakuake-session#16]
I use the Fish shell and the output I get from any `yakuake-session` call is the following:

```
 . '/tmp/yakuake-session-Z3JdLxrNNX'
[14:13:30]-[~]                                                                                                                                                                                              
[hp6-clima-10.ictp.it]->   . '/tmp/yakuake-session-Z3JdLxrNNX'
Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
/tmp/yakuake-session-Z3JdLxrNNX (line 2): true && cd /afs/ictp.it/home/a/afantini && exec ssh_marconi 
                                                ^
from sourcing file /tmp/yakuake-session-Z3JdLxrNNX
        called on line 151 of file /usr/share/fish/config.fish

in function '.'
        called on standard input

source: Error while reading file '/tmp/yakuake-session-Z3JdLxrNNX'
```
This does not happen if I set Bash as the default shell to start in the Yakuake profile.

**Comment by aplatanado** [comment]
Yes. yakuake-session creates a script file which run inside the new Yakuake session. That file is compatible with bash. You can see it at:

https://github.com/aplatanado/yakuake-session/blob/master/yakuake-session#L278

But fish doesn't understand && operator. In fish the line:

~~~
$(profile_setup_command) && cd $(printf %q "$cwd") && $cmd
~~~

should be:

~~~
$(profile_setup_command); and $(printf %q "$cwd"); and $cmd
~~~

but it will not work in bash. So I don't know how to do that line works in fish and in bash compatible shell.
I guess I could detect the shell family and write a line or another for every case.

**Comment by Zardoz89** [comment]
This bug is happening yet : 

> Welcome to fish, the friendly interactive shell
> Type help for instructions on how to use fish
>  ~   source '/tmp/yakuake-session-KyDy1hmH65'                                                                                                                                                                                         
> /tmp/yakuake-session-KyDy1hmH65 (line 5): Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
> cd /home/luis && true
>                ^
> from sourcing file /tmp/yakuake-session-KyDy1hmH65
>         called on standard input
> 
> source: Error while reading file '/tmp/yakuake-session-KyDy1hmH65'

cat /tmp/yakuake-session-KyDy1hmH65
```
clear
rm -f '/tmp/yakuake-session-KyDy1hmH65' 2>/dev/null
true
if [ -z "$FISH_VERSION" ]; then
  cd /home/luis && true
else
  cd /home/luis; and true
fi
```


More info :
Commit 5f83934
Fish-> fish --version 
fish, version 2.7.1
kUbuntu 18.04.1
