### ISSUE TITLE
Working directory can't be canged

### ISSUE THREAD

**Issue by Vavooon** [aplatanado/yakuake-session#17]
I'm trying to open Yakuake tab with desired working directory.
I'm running 
`yakuake-session  -w /`
however, new tab is always opened in home directory.

**Comment by aplatanado** [comment]
Thank you for your report.

In the last commit to fix #16 I caused a regression. I must found another way to solve #16.
You could use 99cb908 meanwhile. It is the commit before the regression.

**Comment by Vavooon** [comment]
Thank you, it works if I use this commit.

**Comment by aplatanado** [comment]
Fix in c33e266

**Comment by Vavooon** [comment]
Finally managed to try it, thanks.
However it requires to install _wmctrl_ so you may want to mention it in readme.

**Comment by aplatanado** [comment]
Yes. We mention it here: https://github.com/aplatanado/yakuake-session#bugs--known-issues
Do you think it could better in other section?

**Comment by Vavooon** [comment]
I'm sorry, missed it :)
I was looking in "Installation", so IMHO there could be "Requirements" section there.
