### ISSUE TITLE
Not working in 3.0.4

### ISSUE THREAD

**Issue by alexivkin** [aplatanado/yakuake-session#18]
The latest version of yakuake refuses to execute runCommand over DBUS citing security issues, and suggests recompiling itself. Any way to solve it without having to recompile yakuake?

**Comment by alexivkin** [comment]
any luck?

**Comment by alexivkin** [comment]
Turns out this was related to a subshell change. Created a pull request #19 to fix. The security warning is just that, a warning, yakuake runcommand is working

**Comment by aplatanado** [comment]
Then this is a dup of #17 and is caused for a regression introduced in 2c0d96c trying to fix #16.
Thank you @alexivkin
