### ISSUE TITLE
execute command in existing session?

### ISSUE THREAD

**Issue by vspinu** [aplatanado/yakuake-session#25]
Hi,

Thanks for the really nice kit! 

I would like to be able to send commands and set wd into an existing yakuake session. Is this possible or could be made possible? Whatever I have tried does open a new session. 

Thanks.

**Comment by aplatanado** [comment]
Hi,

It is possible but you don't need yakuake-session. Just run:

~~~
qdbus org.kde.yakuake /yakuake/sessions runCommand "your_command"
~~~

in command line. "your_command" will run in the current active Yakuake session.

**Comment by vspinu** [comment]
Perfect!  Thanks.
